<?php

namespace App\Console\Commands;

use App\Services\SerialCostRemediationApprovalService;
use Illuminate\Console\Command;
use JsonException;
use RuntimeException;

class CreateSerialCostRemediationApproval extends Command
{
    protected $signature = 'costing:approve-serial-remediation
        {--plan-json= : Required plan JSON generated by costing:plan-serial-remediation}
        {--invoice=* : Exact invoice codes selected for this approval batch}
        {--limit= : Explicit positive deterministic line limit when invoice codes are not supplied}
        {--approved-by= : Required independent accounting approver identity}
        {--approval-reference= : Required accounting ticket, document, or sign-off reference}';

    protected $description = 'Create a separate approval artifact for a small, exact serial COGS remediation batch.';

    public function handle(SerialCostRemediationApprovalService $approvals): int
    {
        try {
            $plan = $this->readJsonFile((string) ($this->option('plan-json') ?? ''), 'plan');
            $limit = $this->option('limit') === null ? null : (int) $this->option('limit');
            $approval = $approvals->create(
                $plan,
                (array) $this->option('invoice'),
                $limit,
                (string) ($this->option('approved-by') ?? ''),
                (string) ($this->option('approval-reference') ?? ''),
            );
            $this->line(json_encode($approval, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));

            return self::SUCCESS;
        } catch (JsonException|RuntimeException $exception) {
            $this->error($exception->getMessage());

            return self::FAILURE;
        }
    }

    /** @return array<string, mixed> */
    private function readJsonFile(string $path, string $label): array
    {
        if ($path === '' || ! is_file($path)) {
            throw new RuntimeException('Missing '.$label.' JSON file.');
        }

        $payload = json_decode((string) file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);
        if (! is_array($payload)) {
            throw new RuntimeException('Invalid '.$label.' JSON payload.');
        }

        return $payload;
    }
}
