<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttendanceTestEmployeesSeeder extends Seeder
{
    /**
     * Seed employee list used for attendance integration testing.
     */
    public function run(): void
    {
        $now = now();

        DB::table('employees')->upsert([
            [
                'code' => 'NV000029',
                'attendance_code' => null,
                'name' => 'Đỗ Lệ Quyên',
                'phone' => '0988769902',
                'email' => null,
                'cccd' => null,
                'branch_id' => null,
                'department_id' => null,
                'job_title_id' => null,
                'is_active' => true,
                'balance' => 0,
                'notes' => 'Seeded for attendance test',
                'avatar' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'NV000028',
                'attendance_code' => '16',
                'name' => 'Trần Anh Tuấn',
                'phone' => '0355462583',
                'email' => null,
                'cccd' => null,
                'branch_id' => null,
                'department_id' => null,
                'job_title_id' => null,
                'is_active' => true,
                'balance' => 0,
                'notes' => 'Seeded for attendance test',
                'avatar' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'NV000026',
                'attendance_code' => '12',
                'name' => 'Nguyễn Xuân Thành',
                'phone' => '0866461689',
                'email' => null,
                'cccd' => null,
                'branch_id' => null,
                'department_id' => null,
                'job_title_id' => null,
                'is_active' => true,
                'balance' => 0,
                'notes' => 'Seeded for attendance test',
                'avatar' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'NV000024',
                'attendance_code' => '11',
                'name' => 'Sa Đình Cường',
                'phone' => '0975969384',
                'email' => null,
                'cccd' => null,
                'branch_id' => null,
                'department_id' => null,
                'job_title_id' => null,
                'is_active' => true,
                'balance' => 0,
                'notes' => 'Seeded for attendance test',
                'avatar' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'NV000018',
                'attendance_code' => null,
                'name' => 'Nguyễn Văn Long',
                'phone' => '0368228001',
                'email' => null,
                'cccd' => null,
                'branch_id' => null,
                'department_id' => null,
                'job_title_id' => null,
                'is_active' => true,
                'balance' => -66417000,
                'notes' => 'Seeded for attendance test',
                'avatar' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'NV000016',
                'attendance_code' => '4',
                'name' => 'Vũ Hồng Nhung',
                'phone' => '0966886372',
                'email' => null,
                'cccd' => null,
                'branch_id' => null,
                'department_id' => null,
                'job_title_id' => null,
                'is_active' => true,
                'balance' => 0,
                'notes' => 'Seeded for attendance test',
                'avatar' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'NV000012',
                'attendance_code' => null,
                'name' => 'Vũ Thị Thu Thủy',
                'phone' => '0963188990',
                'email' => null,
                'cccd' => null,
                'branch_id' => null,
                'department_id' => null,
                'job_title_id' => null,
                'is_active' => true,
                'balance' => 50000000,
                'notes' => 'Seeded for attendance test',
                'avatar' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['code'], [
            'attendance_code',
            'name',
            'phone',
            'email',
            'cccd',
            'branch_id',
            'department_id',
            'job_title_id',
            'is_active',
            'balance',
            'notes',
            'avatar',
            'updated_at',
        ]);
    }
}
