<?php

return [
    'release_id' => 'debt-pr-d',
    'release_name' => 'Migration PR D debt-offset hardening',
    'expected_previous_production_sha' => '6ed1c198a38a2c8d31e2d67d6cc39e6662485700',
    'expected_database_name_sha256' => 'f274e3270e7608fa98dfd67614230224914f1efd7f468b496cfe0c7376d11288',
    'database_engine' => ['family' => 'MariaDB', 'version_prefix' => '10.11.'],
    'allowed_branch' => 'production-customer-group',
    'preflight_ttl_minutes' => 360,
    'maintenance_required' => true,
    'database_advisory_lock' => 'kiot:debt-release:pr-d',
    'temp_database_pattern' => '/^test_kiot_pr_d_restore_[0-9]{8}_[0-9]{6}_[a-z0-9]{6,16}$/',
    'audit_directory_prefix' => 'debt-pr-d-',
    'backup_filename_prefix' => 'kiot-pr-d-db-backup-',
    'ddl_thresholds' => [
        'active_transaction_seconds' => 30,
        'target_query_seconds' => 5,
    ],
    'migrations' => [
        [
            'stage' => 'migration_1_verified',
            'path' => 'database/migrations/2026_07_17_000000_add_workflow_evidence_columns_to_debt_offsets.php',
            'name' => '2026_07_17_000000_add_workflow_evidence_columns_to_debt_offsets',
        ],
        [
            'stage' => 'migration_2_verified',
            'path' => 'database/migrations/2026_07_17_000100_add_workflow_keys_and_foreign_keys_to_debt_offsets.php',
            'name' => '2026_07_17_000100_add_workflow_keys_and_foreign_keys_to_debt_offsets',
        ],
        [
            'stage' => 'migration_3_verified',
            'path' => 'database/migrations/2026_07_17_000200_add_workflow_checks_to_debt_offsets.php',
            'name' => '2026_07_17_000200_add_workflow_checks_to_debt_offsets',
        ],
    ],
    'target_table' => 'debt_offsets',
    'new_columns' => [
        'workflow_status',
        'requested_by',
        'requested_at',
        'approved_by',
        'approved_at',
        'rejected_by',
        'rejected_at',
        'rejection_reason',
        'applied_at',
        'idempotency_key',
        'approval_operation_id',
        'apply_operation_id',
        'reversal_operation_id',
        'customer_amount',
        'supplier_amount',
        'source_references',
        'reverses_debt_offset_id',
    ],
    'legacy_offset_columns' => [
        'id',
        'code',
        'customer_id',
        'amount',
        'receivable_before',
        'payable_before',
        'receivable_after',
        'payable_after',
        'is_auto',
        'note',
        'user_id',
        'status',
        'cancelled_at',
        'cancelled_by',
        'cancel_reason',
        'created_at',
        'updated_at',
    ],
    'unique_indexes' => [
        'do_idempotency_uq' => ['idempotency_key'],
        'do_reverses_uq' => ['reverses_debt_offset_id'],
    ],
    'foreign_keys' => [
        'do_requested_by_fk' => ['column' => 'requested_by', 'table' => 'users', 'delete' => 'SET NULL'],
        'do_approved_by_fk' => ['column' => 'approved_by', 'table' => 'users', 'delete' => 'SET NULL'],
        'do_rejected_by_fk' => ['column' => 'rejected_by', 'table' => 'users', 'delete' => 'SET NULL'],
        'do_approval_operation_fk' => ['column' => 'approval_operation_id', 'table' => 'partner_debt_operations', 'delete' => 'RESTRICT'],
        'do_apply_operation_fk' => ['column' => 'apply_operation_id', 'table' => 'partner_debt_operations', 'delete' => 'RESTRICT'],
        'do_reversal_operation_fk' => ['column' => 'reversal_operation_id', 'table' => 'partner_debt_operations', 'delete' => 'RESTRICT'],
        'do_reverses_fk' => ['column' => 'reverses_debt_offset_id', 'table' => 'debt_offsets', 'delete' => 'RESTRICT'],
    ],
    'checks' => [
        'do_workflow_status_chk' => ['workflow_status', 'pending_approval', 'reversed'],
        'do_amount_pair_chk' => ['customer_amount', 'supplier_amount'],
        'do_amount_positive_chk' => ['customer_amount', 'supplier_amount'],
        'do_amount_equal_chk' => ['customer_amount', 'supplier_amount', 'amount'],
        'do_rejection_reason_chk' => ['workflow_status', 'rejection_reason', 'rejected'],
        'do_idempotency_nonempty_chk' => ['idempotency_key'],
    ],
    'legacy_customer_foreign_key' => [
        'name' => 'debt_offsets_customer_id_foreign',
        'column' => 'customer_id',
        'table' => 'customers',
        'delete' => 'CASCADE',
    ],
    'invariant_table_groups' => [
        'legacy' => [
            'customers',
            'users',
            'cash_flows',
            'invoices',
            'purchases',
            'customer_debts',
            'supplier_debt_transactions',
            'customer_payment_allocations',
            'debt_offsets',
        ],
        'pr_a' => [
            'partner_debt_operations',
            'partner_debt_operation_participants',
            'partner_debt_outbox_events',
        ],
        'pr_b' => [
            'supplier_payment_allocations',
            'supplier_payment_allocation_reversals',
            'customer_payment_allocation_reversals',
        ],
        'pr_c' => [
            'partner_debt_opening_balances',
            'partner_debt_integrity_incidents',
            'partner_debt_integrity_incident_events',
        ],
    ],
    'financial_aggregates' => [
        'customers' => 'SELECT COUNT(*) AS row_count, COALESCE(SUM(debt_amount), 0) AS amount_1, COALESCE(SUM(supplier_debt_amount), 0) AS amount_2 FROM customers',
        'cash_flows' => 'SELECT COUNT(*) AS row_count, COALESCE(SUM(amount), 0) AS amount_1 FROM cash_flows',
        'invoices' => 'SELECT COUNT(*) AS row_count, COALESCE(SUM(total), 0) AS amount_1, COALESCE(SUM(order_deposit_applied_amount), 0) AS amount_2 FROM invoices',
        'purchases' => 'SELECT COUNT(*) AS row_count, COALESCE(SUM(total_amount), 0) AS amount_1, COALESCE(SUM(paid_amount), 0) AS amount_2, COALESCE(SUM(debt_amount), 0) AS amount_3 FROM purchases',
        'customer_debts' => 'SELECT COUNT(*) AS row_count, COALESCE(SUM(amount), 0) AS amount_1 FROM customer_debts',
        'supplier_debt_transactions' => 'SELECT COUNT(*) AS row_count, COALESCE(SUM(amount), 0) AS amount_1 FROM supplier_debt_transactions',
        'debt_offsets' => 'SELECT COUNT(*) AS row_count, COALESCE(SUM(amount), 0) AS amount_1 FROM debt_offsets',
    ],
    'smoke_paths' => [
        ['path' => '/', 'statuses' => [200, 302]],
        ['path' => '/login', 'statuses' => [200]],
    ],
];
